### ISSUE TITLE
Get iOS Advertising Id

### ISSUE THREAD

**Issue by rmhulle** [rudderlabs/rudder-sdk-ios#117]
All the documentation regards Advertisign it's obsolete, since iOS 14 you should:

Ask for permission (https://developer.apple.com/documentation/apptrackingtransparency):
1 Set up a NSUserTrackingUsageDescription to display a system-permission alert request for your app installed on end-user devices.

2 Call requestTrackingAuthorization(completionHandler:) to present the app-tracking authorization request to the end user.

3 Use trackingAuthorizationStatus to determine the app-tracking permission status. See ATTrackingManager.AuthorizationStatus for status enums.

Then (https://developer.apple.com/documentation/adsupport)

1 Use the AdSupport framework to call the shared() class method to retrieve an instance of ASIdentifierManager.

2 Use the advertisingIdentifier property to obtain the UUID.

Could you guys update that in order to work?

**Comment by desusai7** [comment]
Hey @rmhulle, 

Thank you for pointing out that, we will update our documentation accordingly. 

Actually, Rudder iOS SDK doesn't automatically collect the advertising Id on its own, and the end developer needs to do the entire process and then pass the advertising Id at the end to our `putAdvertisementId` API.

But yeah, we will definitely update the documentation and provide a brief description of the entire process of getting consent and advertising identifier from ASIdentifierManager.

Closing this issue for now.
