### ISSUE TITLE
Crash on `RSContext.m - Ligne 13`

### ISSUE THREAD

**Issue by LiardeauxQ** [rudderlabs/rudder-sdk-ios#128]
Hello, we have integrated the SPM Rudder v1.5.1. Do you have an idea what can cause the following crash ? It happened during one of our automated test on our Release candidate. We tried to open the Application, go to Settings app and then go back to the Application.  iPhone XS 15.3.0
The Rudder iOS SDK is initialise in our AppDelegate's didFinishLaunchingWithOptions method.

<img width="1104" alt="Screenshot 2022-04-15 at 16 06 25" src="https://user-images.githubusercontent.com/34253186/163580782-8c382dd2-9098-4f81-adfa-e69ea7fd71d2.png">
<img width="1106" alt="Screenshot 2022-04-15 at 16 06 35" src="https://user-images.githubusercontent.com/34253186/163580794-633533a8-e1fd-44c2-97bd-96d979c79469.png">
<img width="1107" alt="Screenshot 2022-04-15 at 16 39 36" src="https://user-images.githubusercontent.com/34253186/163584236-385c4037-4f2f-4ecf-a4f2-4b96cebe87d7.png">

Thanks for your time.

**Comment by pallabmaiti** [comment]
We fixed these crashes on version 1.5.2. Please use the latest version.
