### ISSUE TITLE
BUG: SDK crashing on bad exception

### ISSUE THREAD

**Issue by pallabmaiti** [rudderlabs/rudder-sdk-ios#191]
Race conditions were observed in multiple threads.

**Comment by Krythz43** [comment]
@pallabmaiti facing this issue on a production level, is there any tentative fix we can do at our end to make sure this doesn't happen?

**Comment by pallabmaiti** [comment]
V2 is still in beta. We will pick up fixing this issue in Q4. Expect stability of v2 in Q1 of next year.

**Comment by 1abhishekpandey** [comment]
iOS v2 is still in beta. If anyone following this thread, I kindly request them to revert back to v1.
