### ISSUE TITLE
[ISSUE] Rudder crashing

### ISSUE THREAD

**Issue by manav1mg** [rudderlabs/rudder-sdk-ios#196]
[RSEventRepository makeFactoryDump:] 

Crash Stack : 
<img width="516" alt="Screenshot 2022-08-18 at 2 37 37 AM" src="https://user-images.githubusercontent.com/91203002/185243268-8e2d05a0-352f-4606-b125-b3928775b226.png">
<img width="867" alt="Screenshot 2022-08-18 at 2 37 54 AM" src="https://user-images.githubusercontent.com/91203002/185243308-f54203f8-6beb-41f1-88cb-18fe2200a5d3.png">

**Comment by pallabmaiti** [comment]
Hey @manav1mg, you are using a very old version. Can you update to the new version?
