### ISSUE TITLE
Allow consumers to provide their own URLSession

### ISSUE THREAD

**Issue by justindhill** [rudderlabs/rudder-sdk-ios#201]
We use Rudderstack behind a proxy endpoint hosted on our domain. We have TLS certificate pinning in place in our app and would like to provide a URLSession whose delegate performs the pinning enforcement for our domain.

**Comment by pallabmaiti** [comment]
Hey @justindhill, we don't have any roadmap item regarding this enhancement. It will take time, probably next quarter (2023 Q1). If it is urgent, you can contribute. We would love to review your PR.
