### ISSUE TITLE
macOS lifecycle event not logged during app start

### ISSUE THREAD

**Issue by DarkDust** [rudderlabs/rudder-sdk-ios#216]
Our app currently sets up Rudder after `applicationDidFinishLaunching:`. This has the effect that once we do set up `RSClient`, `RSmacOSLifecycleEvents.application(didFinishLaunchingWithOptions:)` is not called until a user switches to another app and switches back. (`RSmacOSLifecycleEvents.applicationDidBecomeActive()` also calls `application(didFinishLaunchingWithOptions:)`.

This in turn means that if a user would start the app and then quits, the "Application Installed/Updated/Opened" events never get logged. Some way to tell Rudder that the app is already app might be useful.

I also tried setting up Rudder during `applicationWillFinishLaunching:`. With the debugger, I can confirm that `RSmacOSLifecycleEvents.application(didFinishLaunchingWithOptions:)` is called, yet the "Application Opened" event is never actually sent. It seems events are only sent after `RSClient.identify` was called (and we cannot do that during `applicationWillFinishLaunching:` as the user can only be accessed much later in the app lifecycle).

**Comment by pallabmaiti** [comment]
The issue has been fixed in version [2.2.5](https://github.com/rudderlabs/rudder-sdk-ios/releases/tag/v2.2.5).
