### ISSUE TITLE
(Crash) EventRepository.m - Line 293

### ISSUE THREAD

**Issue by abhijeetchoudhary1mg** [rudderlabs/rudder-sdk-ios#24]
EventRepository.m - Line 293 Crash in Rudder sdk version 1.0.2

**Comment by arnabp92** [comment]
@abhijeetchoudhary1mg 
The issue is in serialization. Can you send the event payload you are trying to send?

**Comment by arnabp92** [comment]
Fixed the crash:

The supported types for the `properties` and `traits` are: `NSString`, `NSNumber`, `NSNull`, `NSArray`, `NSDictionary<NSString, id>`, `NSDate`, `NSURL`

https://github.com/rudderlabs/rudder-sdk-ios/commit/64792ecd18547454551cd7c3350535eedbae2ce9
