### ISSUE TITLE
BUG : Fails to Send Events Due to SQLite Insert Error

### ISSUE THREAD

**Issue by DoraemonEXA** [rudderlabs/rudder-sdk-ios#317]
**Describe the bug**
In the latest version of the Rudder SDK for iOS, the `saveEvent` method in `RSDBPersistentManager` uses an `INSERT` SQL statement with a `RETURNING` syntax that is only supported in SQLite version 3.35.0 or higher. 

https://github.com/rudderlabs/rudder-sdk-ios/blob/79ecaad45b988fa90fa1f5ddafa6824193bb8ab8/Sources/Classes/RSDBPersistentManager.m#L107

However, when the SDK runs on iOS versions earlier than 15.0, which use SQLite version 3.32.3, the `INSERT` statement fails. This prevents the SDK from sending events.

After reviewing the commit history, I found that `RSDBPersistentManager` in version 1.13.2 does not use the `RETURNING` syntax. I tested this version on my iPhone running iOS 14.4 and confirmed that events are successfully sent to my data plane.

**Version of the _iOS_ SDK**
1.15.0

**Check for Correct Usage of _writeKey_ and _dataPlaneUrl_**
Yes

**Comment by pallabmaiti** [comment]
Thanks, @DoraemonEXA, for raising the issue. We are working on a fix. Soon, we release a fix.

**Comment by desusai7** [comment]
Hey @DoraemonEXA ,

We released a fix for this issue in version `1.15.1`, can you please upgrade to this version to solve the issue.

**Comment by DoraemonEXA** [comment]
> Hey @DoraemonEXA ,
> 
> We released a fix for this issue in version `1.15.1`, can you please upgrade to this version to solve the issue.

The issue has been resolved on older iOS versions with the latest SDK. Thank you😉
