### ISSUE TITLE
Escape ' symbol in event data

### ISSUE THREAD

**Issue by InkOut** [rudderlabs/rudder-sdk-ios#34]
If you send property with ' symbol, that will cause an error

It's better to replace all ' symbols with ''

https://github.com/rudderlabs/rudder-sdk-ios/blob/782c76158f9d4df31c1da73160fb95b692152e86/Rudder/Classes/RSDBPersistentManager.m#L50

Android SDK does it:

https://github.com/rudderlabs/rudder-sdk-android/blob/07484c210c252b3c07320654a7185155e3cf8238/core/src/main/java/com/rudderstack/android/sdk/core/DBPersistentManager.java#L47

And please, update React Native Library after it

**Comment by arnab-p** [comment]
Thanks @InkOut for pointing out. We'll fix it soon.
