### ISSUE TITLE
BUG : Build error on versions after 1.17.0, using Packages dependencies

### ISSUE THREAD

**Issue by bmoliveira** [rudderlabs/rudder-sdk-ios#372]
**Describe the bug**
Please provide the following information:

1. A clear and concise description of what the bug is

Using the Xcode swift packages dependencies manager, I started getting this error building:

`Module 'MetricsReporter' not found` on `RSMetricsReporter.m`.

~2. Share the event payload~
~3. Offer a minimal viable example to reproduce the issue~
~4. Indicate if the SDK is being initialized or events are being created on a separate thread or coroutine apart from the main thread~
~5. Specify if the issue is specific to a particular device model or OS version~
~6. Include the error's stack trace~
7. Mention the date when the issue began

After updating to a newer release after 1.17.0.

**To Reproduce**
Steps to reproduce the behaviour:

1. Update to version 1.18.0, 1.19.0 or 1.19.1
2. Try to build
3. See the error.

**Expected behavior**
Build the App 🚀 

**Screenshots**

<img width="1159" alt="Screenshot 2023-08-23 at 15 18 45" src="https://github.com/rudderlabs/rudder-sdk-ios/assets/1921410/4f0e44fd-c80d-4680-96c5-acd418fa9440">

**Version of the _iOS_ SDK**
1.18.0, 1.19.0 or 1.19.1

**Mobile device mode integration**
N/A

**SDK initialisation snippet**
N/A

**Comment by pallabmaiti** [comment]
We will release it next week.

**Comment by bmoliveira** [comment]
Thank you for the help 🙏
