### ISSUE TITLE
BUG : Unsafe flags make the library only usable with target branch

### ISSUE THREAD

**Issue by bmoliveira** [rudderlabs/rudder-sdk-ios#379]
**Describe the bug**

With [the addition](https://github.com/rudderlabs/rudder-sdk-ios/blame/abb2ee358e50620b7a7b92b6363735657d9a7eae/Package.swift#L30) of `. unsafeFlags` makes the BuildManager throw an exception while building (using lib with versions).

Reference discussion and other similar issues: 

 - https://github.com/apple/swift-package-manager/pull/2254
 - https://forums.swift.org/t/override-for-unsafeflags-in-swift-package-manager/45273

For now, I still can use the `master` branch instead of using a specific version, and the app is building and the SDK working.

Details:
- Using SPM.
- SDK version: v1.19.2 (now using master branch).

**Comment by pallabmaiti** [comment]
This sample [app](https://drive.google.com/file/d/1oxI0iDTnox_sPqntcn_L77Ud1tm7RX2q/view?usp=sharing) uses the specific version; I am not getting any exceptions.

**Comment by bmoliveira** [comment]
This is the error that I have while building using version :

<img width="714" alt="Screenshot 2023-08-30 at 11 04 35" src="https://github.com/rudderlabs/rudder-sdk-ios/assets/1921410/0007d630-2fa4-4161-afe3-3a43d3633c90">

Downloading the sample and trying it out I have the same error:

<img width="1493" alt="Screenshot 2023-08-30 at 11 07 40" src="https://github.com/rudderlabs/rudder-sdk-ios/assets/1921410/69199204-34a5-4b06-8c1b-cd734cd74092">

Maybe it's the Xcode version that is different?

**Comment by pallabmaiti** [comment]
Weird using the same Xcode version.
<img width="1512" alt="Screenshot 2023-08-30 at 6 56 05 PM" src="https://github.com/rudderlabs/rudder-sdk-ios/assets/17945096/460e9e00-9257-42d1-ad2b-d47097c79931">

**Comment by pallabmaiti** [comment]
Were you able to solve it?

**Comment by bmoliveira** [comment]
I can still use the lib referencing a branch or a commit. From the MR into Swift, the unsafe check is overridden when using branch or commit, that's why I can still use it.

**Comment by ekurutepe** [comment]
I just updated from 1.13.2 to 1.19.2. Getting the same error on Xcode 15b8

**Comment by pallabmaiti** [comment]
Will look into this.

**Comment by harryblam** [comment]
Can confirm i'm getting the same error when using SPM from my Xcode project (Xcode 15 beta 7, Rudder v1.19.2).

<img width="323" alt="Screenshot 2023-09-05 at 16 23 55" src="https://github.com/rudderlabs/rudder-sdk-ios/assets/2333536/9065e729-0182-47d1-9017-4d151348cc19">

**Comment by pallabmaiti** [comment]
We are working on it.

**Comment by harryblam** [comment]
For visibility, I've now changed to use `[v2.4.2](https://github.com/rudderlabs/rudder-sdk-ios/releases/tag/v2.4.2)` and that version works without a hitch.

I should have done that initially but I missed the fact a v2 existed as the project README still recommends 1.19.2.

**Comment by pallabmaiti** [comment]
@harryblam v2 is in beta. We don't recommend it.
