### ISSUE TITLE
BUG : Unable to build .xcframework for v1.18.x & v1.19.x

### ISSUE THREAD

**Issue by zjaindiv26** [rudderlabs/rudder-sdk-ios#382]
**Describe the bug**
Please provide the following information:

1. A clear and concise description of what the bug is: While updating, we observed that xcframework is not able to build for v1.18.0 and above. But for v1.17.0 it's working fine
2. Share the event payload
3. Offer a minimal viable example to reproduce the issue
4. Indicate if the SDK is being initialized or events are being created on a separate thread or coroutine apart from the main thread
5. Specify if the issue is specific to a particular device model or OS version
6. Include the error's stack trace
7. Mention the date when the issue began

**To Reproduce**
Steps to reproduce the behaviour:

1. Initialise iOS SDK
2. Make events '....'
3. See the error

**Expected behavior**

**Screenshots**

**Version of the _iOS_ SDK**
Please mention the version of the Rudder iOS SDK you are using (e.g., iOS SDK v1.0.0).

**Mobile device mode integration**
Please provide the following information:

1. `Name` and `version` of the mobile device mode integration (e.g., RudderAmplitude iOS v1.0.0 mobile device mode integration)
2. Indicate if you are using the native SDK directly and specify its version (e.g., Amplitude native iOS SDK v2.0.0)

**SDK initialisation snippet**
Please provide the following information:

1. Share the code snippet used for initializing the iOS SDK
2. Indicate if the SDK initialization depends on any specific condition or event (e.g., initialization of the iOS SDK after Firebase initialization or initialization in a callback)

**Check for Correct Usage of _writeKey_ and _dataPlaneUrl_**
Confirm that the correct `writeKey` and `dataPlaneUrl` are utilized during SDK initialization.

<img width="1436" alt="Screenshot 2023-08-31 at 1 20 58 PM" src="https://github.com/rudderlabs/rudder-sdk-ios/assets/123928948/b902d710-ecac-4b5d-a84e-bac068cf1ce3">

[Logv1.18.0.txt](https://github.com/rudderlabs/rudder-sdk-ios/files/12483861/Logv1.18.0.txt)

**Comment by pallabmaiti** [comment]
We are looking into this.

**Comment by zjaindiv26** [comment]
@pallabmaiti We've integrated rudder as a Carthage dependency. And we're unable to build Carthage for v1.8.x and v1.19.x version. While v1.17.0 is building fine. It's seems to be a podfile.lock mismatch due. Please have a look into this.

**Comment by 1abhishekpandey** [comment]
Hey @zjaindiv26,
We have introduced support for XCFramework files in our iOS SDKs starting from version 1.25.0 onwards. You may utilise that.
