### ISSUE TITLE
BUG : SPM issue

### ISSUE THREAD

**Issue by EvgeniyGT** [rudderlabs/rudder-sdk-ios#386]
SDK version: 1.19.2

After package has been added. Project wan't compile with error: 

> The package product 'Rudder' cannot be used as a dependency of this target because it uses unsafe build flags.

This can be reproduced on new absolutely clean Xcode project.

**Comment by pallabmaiti** [comment]
We have fixed this issue in #384, and it will be pushed to the coming week.
