### ISSUE TITLE
Using rudder-sdk-ios to create xamarin binding

### ISSUE THREAD

**Issue by gideonairex** [rudderlabs/rudder-sdk-ios#41]
**[QUESTION]**
1. I want to create Xamarin binding for rudder-sdk-ios but got stuck on the apiDefinition cause it created around 70k lines that I need to fix manually. Is there an alternative for this? I know this is not related directly to your library.

**[OBJECTIVE]**
1. Create a binding for Xamarin using the rudder-sdk-ios.
Note: The reason why I didnt create a Rudder http client on Xamarin is that your SDK has management for offline use. Thinking it would be easier.

**[PROBLEM]**
1. when running lipo to create ApiDefinition and Struct from the *.h files it generated around 70k lines. That needs to be updated manually.

**Comment by desusai7** [comment]
Hey @gideonairex, 
We are not supporting Xamarin Binding for our Rudder-SDK-iOS. I Will let you know if we support it in future.
