### ISSUE TITLE
REQUEST: `.xcframework` for version > 2.0.0

### ISSUE THREAD

**Issue by mabdullahsaeed** [rudderlabs/rudder-sdk-ios#410]
In our organization we use a CI/CD platform to build and release our iOS apps. Dependencies added through Pods, Carthage or SPM makes the build process slower on the Github runner. 
It would be great to include `.xcframework` files for the latest version for the people who want to manually add this into the Xcode project without using any dependency manager.

**Comment by 1abhishekpandey** [comment]
Thank you for submitting this request. I have forwarded it to our team for further review and consideration.
CC: @pallabmaiti

**Comment by 1abhishekpandey** [comment]
Hey @mabdullahsaeed,
We have provided support for the XCFramework for version 1 (1.0.0 to <2.0.0) of our iOS SDK, you may refer to the latest release: https://github.com/rudderlabs/rudder-sdk-ios/releases/tag/v1.25.1.
PS: Version 2 (>=2.0.0) of our iOS SDK is still in beta, once we release the stable version of it, we will provide the same support over there as well.
