### ISSUE TITLE
BUG : In v1.25.0, when doing pod install, terminal outputs: Unable to read the license file

### ISSUE THREAD

**Issue by sof9816** [rudderlabs/rudder-sdk-ios#463]
When trying to install pods, it returns:
`[!] Unable to read the license file `LICENSE` for the spec `Rudder (1.25.0)``
<img width="712" alt="Screenshot 2024-02-07 at 10 08 29 AM" src="https://github.com/rudderlabs/rudder-sdk-ios/assets/29151929/f857ee3b-38d3-4d0b-af5f-23be293efd3f">

**Comment by pallabmaiti** [comment]
We will fix this and release a version soon.

**Comment by 1abhishekpandey** [comment]
Hey @sof9816,
We fixed this in v1.25.1. Please utilise that.
