### ISSUE TITLE
BUG: Calling configure() multiple times keeps adding the same plugins

### ISSUE THREAD

**Issue by ElieJacquelin** [rudderlabs/rudder-sdk-ios#468]
**Version**
Rudder 2.4.3

**Bug description**
Calling `RSClient.sharedInstance().configure(with: config)` causes [plugins to be added multiple times](https://github.com/rudderlabs/rudder-sdk-ios/blob/master-v2/Sources/Classes/Client/RSClient.swift#L47)

If clients regularly calls the `configure()` function, it would result in an ever growing list of plugins which will impact the app performance.

In my case, we would call `configure()` on every screen as it was deemed to be safe, this resulted in significant performance issue where lifecycle events would block the main thread for several seconds.

**Expected outcome**
`RSClient.sharedInstance().configure(with: config)`  should not add plugins that have already been added before. Old plugin instances should be either removed or updated with the new config if needed.

More generally the configure function should be safe to call multiple times.

**Comment by pallabmaiti** [comment]
configure(with:) is 1 time job. It should be called once while initializing the SDK. It is not good practice. We don't encourage or recommend it. Calling multiple times can result to issues.
