### ISSUE TITLE
BUG : Rudder stack compile error after update 

### ISSUE THREAD

**Issue by hamed-ice** [rudderlabs/rudder-sdk-ios#474]
Since yesterday, after updating my packages to the latest versions, I have encountered issues with the Rudder stack. Before this update, I had forked the [Rudder Firebase Integration](https://github.com/hamed-ice/rudder-integration-firebase-swift) and [Rudder Facebook App Events Integration](https://github.com/rudderlabs/rudder-integration-facebook-app-events-swift) repositories and made them SPM compatible. Everything was functioning as expected until the update. I removed my forks SPM and I saw you made them SMP support, but it didn't work I also copied the mentioned SDK(Facebook and Firebase Destination) files to my project instead of using SDK it didn't work, also I wanted to mention firebase SDK is not usync with last version of Firebase

To Reproduce

Initialize the Rudder iOS SDK.
Utilize the Firebase and Facebook App Events integrations.
Encounter compilation errors related to Rudder SDK.
Expected behavior
The Rudder stack should compile without errors and function as expected with the Firebase and Facebook App Events integrations.
 this is CI/CD errors
```

Showing All Errors Only
Cannot find 'PluginType' in scope

Cannot find 'RSController' in scope

Cannot find type 'RSServerConfig' in scope

Cannot find type 'UpdateType' in scope

Cannot find type 'IdentifyMessage' in scope

Cannot find type 'IdentifyMessage' in scope

Cannot find type 'TrackMessage' in scope

Cannot find type 'TrackMessage' in scope

Cannot find type 'ScreenMessage' in scope

Cannot find type 'ScreenMessage' in scope

Cannot find type 'RSDestinationPlugin' in scope

Initializer does not override a designated initializer from its superclass

Cannot find type 'RudderDestination' in scope

Only classes that inherit from NSObject can be declared @objc

Cannot infer contextual base in reference to member 'initial'

Value of type 'RSClient' has no member 'log'

Cannot infer contextual base in reference to member 'warning'

Value of type 'RSClient' has no member 'log'

Cannot infer contextual base in reference to member 'debug'

Value of type 'RSClient' has no member 'log'

Cannot infer contextual base in reference to member 'debug'

Cannot find 'RSLogLevel' in scope

Cannot find 'RSLogLevel' in scope

Value of type 'RSClient' has no member 'log'

Cannot infer contextual base in reference to member 'debug'

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Type of expression is ambiguous without a type annotation

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSEvents' in scope

Cannot find 'RSEvents' in scope

Cannot find 'RSEvents' in scope

Cannot find 'RSEvents' in scope

Cannot find 'RSEvents' in scope

Cannot find 'RSEvents' in scope

Cannot find 'RSEvents' in scope

Cannot find 'RSEvents' in scope

Cannot find 'RSEvents' in scope

Cannot find 'RSEvents' in scope

Cannot find 'RSEvents' in scope

Cannot find 'RSEvents' in scope

Cannot find 'RSEvents' in scope

Cannot find 'RSEvents' in scope

Cannot find 'RSEvents' in scope

Cannot find 'RSEvents' in scope

Cannot find 'RSEvents' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

Cannot find 'RSKeys' in scope

'super' members cannot be referenced in a root class

Cannot find 'plugin' in scope


```

Using Rudder iOS SDK version v2.4.3

Mobile device mode integration: arm64

Rudder Firebase Integration v1.1.0 SPM support.
Rudder Facebook App Events Integration v1.1.0 SPM support.
SDK initialization snippet
```Swift
let config: RSConfig = RSConfig(writeKey: Discovery.shared.iceLogConfigs.writeKey)
      .dataPlaneURL(Discovery.shared.iceLogConfigs.dataPanelUrl)
      .loglevel(RSLogLevel.debug)
      .controlPlaneURL(Discovery.shared.iceLogConfigs.controlPanelUrl)
      .recordScreenViews(true)
      .sessionTimeout(1800000)
    Async.main {
      RSClient.sharedInstance().configure(with: config)
    }
 
 ```
![Screenshot 2024-02-22 at 3 30 31 PM](https://github.com/rudderlabs/rudder-sdk-ios/assets/129689306/acb810f5-2f36-4cd8-b475-a9b6d7145a4e)

Additional Details
I attempted to resolve the issue by updating to the latest versions of the Rudder integrations with SPM support. However, the issue persisted. Also, attempting to copy the RSFacebookAppEventsDestination and RSFirebaseDestination classes directly resulted in the same compilation errors.

Date When the Issue Began
Feb 21, 2023

**Comment by desusai7** [comment]
Hi @hamed-ice, 

We will check this and get back to you.

**Comment by hamed-ice** [comment]
Hi @desusai7 thank you, it blocked me, if it's possible check it sooner

**Comment by desusai7** [comment]
@hamed-ice, this issue seems to be due to an incorrect tag created for version 2.4.3. We've fixed this, can you try clearing the cache and check if this issue is resolved ?

**Comment by desusai7** [comment]
@hamed-ice, marking this issue as closed for now. But feel free to re-open it if the issue persists.
