### ISSUE TITLE
BUG : Docs for Swift Package Manager use the SSH clone URL, not the HTTPS one

### ISSUE THREAD

**Issue by mraspberry** [rudderlabs/rudder-sdk-ios#489]
**Describe the bug**
The [docs](https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-ios-sdk/#swift-package-manager) reference the SSH clone URL for this repository. This works fine when building locally but it breaks in a CI/CD environment because the pipelines do not have SSH keys usually. The HTTPS URL of this repository should be used instead.

**To Reproduce**

1. Follow the docs as written to add the Rudder iOS SDK to a project using the Swift Package Manager
2. Try to build the project in a CI environment such as Github Actions

**Expected behavior**
The dependency in the CI environment is successfully added and the project is able to be built.

**Screenshots**
![image](https://github.com/rudderlabs/rudder-sdk-ios/assets/3092450/fd290793-df38-4cac-8e1c-f95de4545601)

**Version of the _iOS_ SDK**
iOS SDK 1.26.0

**Comment by 1abhishekpandey** [comment]
Hey @mraspberry,
Thanks for raising this issue. We will look into it and get back to you.

**Comment by desusai7** [comment]
Hey @mraspberry, 

We've updated this in the docs [here](https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-ios-sdk/#swift-package-manager)
