### ISSUE TITLE
v1.16.0 SwiftPM security alert

### ISSUE THREAD

**Issue by MaximBazarov** [rudderlabs/rudder-sdk-ios#492]
When trying to resolve `v1.16.0` which was not changed on our end SwiftPM gives a security error:
> Revision ddf7f08c188f4556e84a75a073026013820142f2 for rudder-sdk-ios remoteSourceControl https://github.com/rudderlabs/rudder-sdk-ios.git version 1.16.0 does not match previously recorded value c4c9b4805ea76a3f2e137cfb7552a33b653be5b7

Did you move the tag by any chance?

**Comment by desusai7** [comment]
Hello @MaximBazarov, 

We have not changed anything around the tag for v1.16.0, it is the same since last June.

**Comment by MaximBazarov** [comment]
thank you for the info @desusai7 than it seems to be our setup, my apology
