### ISSUE TITLE
BUG : Compilation fails due to missing method in `RSMetricConfiguration`

### ISSUE THREAD

**Issue by angelolloqui** [rudderlabs/rudder-sdk-ios#529]
**Describe the bug**
When trying to install RudderStack v 1.28.0 I get the following compilation error:

```No visible @interface for 'RSMetricConfiguration' declares the selector 'initWithLogLevel:writeKey:sdkVersion:'```
as part of the init of the `RSMetricReporter`:
```

- (instancetype)initWithWriteKey:(NSString *)writeKey preferenceManager:(RSPreferenceManager *)preferenceManager andConfig:(RSConfig *)config {
    self = [super init];
    if (self) {
        if (preferenceManager.isMetricsCollectionEnabled || preferenceManager.isErrorsCollectionEnabled) {
            RSMetricConfiguration *configuration = [[RSMetricConfiguration alloc] initWithLogLevel:config.logLevel writeKey:writeKey sdkVersion:RS_VERSION];     //  ---> This line here fails!!
            [configuration dbCountThreshold:config.dbCountThreshold];
            _metricsClient = [[RSMetricsClient alloc] initWithConfiguration:configuration];
            _metricsClient.isMetricsCollectionEnabled = preferenceManager.isMetricsCollectionEnabled;
            _metricsClient.isErrorsCollectionEnabled = preferenceManager.isErrorsCollectionEnabled;
        } else {
            [RSLogger logWarn:@"RSMetricsReporter: Metrics and Errors collection is disabled."]; 
        }
    }
    return self;
}
```

I am integrating it using [Tuist](https://tuist.io/) and SPM:

```
        .package(url: "https://github.com/rudderlabs/rudder-sdk-ios", exact: "1.28.0"),
```

**To Reproduce**
Steps to reproduce the behaviour:

1. Setup a new project (preferably using Tuist but I believe it will happen in a vanilla project too)
2. Add Rudder
3. Compile and check the error

**Expected behavior**
It should compile without issues

**Screenshots**
![Screenshot 2024-08-30 at 11 57 08](https://github.com/user-attachments/assets/bf799c21-baab-4c50-823a-c55f995ffb9b)

**Version of the _iOS_ SDK**
Rudder version 1.28.0
Xcode version 15.4

**Comment by MoumitaM** [comment]
Hi @angelolloqui,
Thank you for raising this. We are looking into it.

**Comment by angelolloqui** [comment]
Thanks! I believe this change from yesterday is the source: https://github.com/rudderlabs/metrics-reporter-ios/pull/43

It is currently breaking our pipeline, so it is quite urgent for us...

**Comment by SKannaniOS** [comment]
Hi @angelolloqui, 

First of all thank you for raising this issue. Also thank you for proposing the solution by opening the PR. 
For now we resolved this issue:

- We have removed the latest tag from Github, so that the projects of our clients can be built as normal again.
- If you are still facing problems, you need to
   - Clean the DerivedData  either by following this [link](https://www.swiftanytime.com/blog/how-to-delete-derived-data-in-xcode) or by using the below command
`rm -rf ~/Library/Developer/Xcode/DerivedData`

- To make sure everything working fine, you can remove and add the package again. 

Let us know, If this solves your issue.

**Comment by angelolloqui** [comment]
Hi @SKannaniOS,

I have tried several things, including cleaning all my previous caches and derived data, and all cases seem to work now.

Thanks very much! and great response time!
